[package]
name = "vienna-time"
version = "0.1.0"
edition = "2021"
authors = ["Andreas Landgraf <andreas.landgraf@ses-imagotag.com>"]
readme = "README.md"
license = "MIT"

[dependencies]
libc = "~0.2"
curl-sys = { git = "https://github.com/alexcrichton/curl-rust.git" }